<a href="https://colab.research.google.com/github/Anubhav-maurya6386/INTRANSHIP_TASK/blob/main/DataPreprocessingChurn_Bigml_20Task1(1).ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# Import Required Libraries

In [1]:
import pandas as pd
import numpy as np

from sklearn.preprocessing import LabelEncoder, StandardScaler
from sklearn.model_selection import train_test_split

# Load Dataset

In [2]:
df = pd.read_csv('churn-bigml-20.csv')
df.head()

,State,Account length,Area code,International plan,Voice mail plan,Number vmail messages,Total day minutes,Total day calls,Total day charge,Total eve minutes,Total eve calls,Total eve charge,Total night minutes,Total night calls,Total night charge,Total intl minutes,Total intl calls,Total intl charge,Customer service calls,Churn
0,LA,117,408,No,No,0,184.5,97,31.37,351.6,80,29.89,215.8,90,9.71,8.7,4,2.35,1,False
1,IN,65,415,No,No,0,129.1,137,21.95,228.5,83,19.42,208.8,111,9.40,12.7,6,3.43,4,True
2,NY,161,415,No,No,0,332.9,67,56.59,317.8,97,27.01,160.6,128,7.23,5.4,9,1.46,4,True
3,SC,111,415,No,No,0,110.4,103,18.77,137.3,102,11.67,189.6,105,8.53,7.7,6,2.08,2,False
4,HI,49,510,No,No,0,119.3,117,20.28,215.1,109,18.28,178.7,90,8.04,11.1,1,3.00,1,False

In [3]:
print(df.shape)
print(df.info())
print(df.describe())

(667, 20)
<class 'pandas.core.frame.DataFrame'>
RangeIndex: 667 entries, 0 to 666
Data columns (total 20 columns):
 #   Column                  Non-Null Count  Dtype
---  ------                  --------------  -----
 0   State                   667 non-null    object
 1   Account length          667 non-null    int64
 2   Area code               667 non-null    int64
 3   International plan      667 non-null    object
 4   Voice mail plan         667 non-null    object
 5   Number vmail messages   667 non-null    int64
 6   Total day minutes       667 non-null    float64
 7   Total day calls         667 non-null    int64
 8   Total day charge        667 non-null    float64
 9   Total eve minutes       667 non-null    float64
 10  Total eve calls         667 non-null    int64
 11  Total eve charge        667 non-null    float64
 12  Total night minutes     667 non-null    float64
 13  Total night calls       667 non-null    int64
 14  Total night charge      667 non-null    float64
 15  Total intl minutes      667 non-null    float64
 16  Total intl calls        667 non-null    int64
 17  Total intl charge       667 non-null    float64
 18  Customer service calls  667 non-null    int64
 19  Churn                   667 non-null    bool
dtypes: bool(1), float64(8), int64(8), object(3)
memory usage: 99.8+ KB
None
       Account length   Area code  Number vmail messages  Total day minutes  \
count      667.000000  667.000000             667.000000         667.000000
mean       102.841079  436.157421               8.407796         180.948126
std         40.819480   41.783305              13.994480          55.508628
min          1.000000  408.000000               0.000000          25.900000
25%         76.000000  408.000000               0.000000         146.250000
50%        102.000000  415.000000               0.000000         178.300000
75%        128.000000  415.000000              20.000000         220.700000
max        232.000000  510.000000              51.000000         334.300000

       Total day calls  Total day charge  Total eve minutes  Total eve calls  \
count       667.000000        667.000000         667.000000       667.000000
mean        100.937031         30.761769         203.355322       100.476762
std          20.396790          9.436463          49.719268        18.948262
min          30.000000          4.400000          48.100000        37.000000
25%          87.500000         24.860000         171.050000        88.000000
50%         101.000000         30.310000         203.700000       101.000000
75%         115.000000         37.520000         236.450000       113.000000
max         165.000000         56.830000         361.800000       168.000000

       Total eve charge  Total night minutes  Total night calls  \
count        667.000000           667.000000         667.000000
mean          17.285262           199.685307         100.113943
std            4.226160            49.759931          20.172505
min            4.090000            23.200000          42.000000
25%           14.540000           167.950000          86.000000
50%           17.310000           201.600000         100.000000
75%           20.095000           231.500000         113.500000
max           30.750000           367.700000         175.000000

       Total night charge  Total intl minutes  Total intl calls  \
count          667.000000          667.000000        667.000000
mean             8.985907           10.238381          4.527736
std              2.239429            2.807850          2.482442
min              1.040000            0.000000          0.000000
25%              7.560000            8.600000          3.000000
50%              9.070000           10.500000          4.000000
75%             10.420000           12.050000          6.000000
max             16.550000           18.300000         18.000000

       Total intl charge  Customer service calls
count         667.000000              667.000000
mean            2.764948                1.563718
std             0.758167                1.333357
min             0.000000                0.000000
25%             2.320000                1.000000
50%             2.840000                1.000000
75%             3.255000                2.000000
max             4.940000                8.000000

# Handle Missing Values

In [4]:
df.isnull().sum()

State                     0
Account length            0
Area code                 0
International plan        0
Voice mail plan           0
Number vmail messages     0
Total day minutes         0
Total day calls           0
Total day charge          0
Total eve minutes         0
Total eve calls           0
Total eve charge          0
Total night minutes       0
Total night calls         0
Total night charge        0
Total intl minutes        0
Total intl calls          0
Total intl charge         0
Customer service calls    0
Churn                     0
dtype: int64

In [5]:
df.fillna(df.mean(numeric_only=True), inplace=True)

# Encode Categorical Variables

In [6]:
df.select_dtypes(include=['object']).columns

Index(['State', 'International plan', 'Voice mail plan'], dtype='object')

# Label Encoding

In [7]:
le = LabelEncoder()

df['State'] = le.fit_transform(df['State'])
df['International plan'] = le.fit_transform(df['International plan'])
df['Voice mail plan'] = le.fit_transform(df['Voice mail plan'])

In [8]:
df['Churn'] = df['Churn'].astype(int)

# Feature Scaling (Normalization / Standardization)

In [9]:
X = df.drop('Churn', axis=1)
y = df['Churn']

In [10]:
scaler = StandardScaler()
X_scaled = scaler.fit_transform(X)

In [11]:
X_scaled = pd.DataFrame(X_scaled, columns=X.columns)

# Split Dataset (Training and Testing)

In [12]:
X_train, X_test, y_train, y_test = train_test_split(
    X_scaled, y, test_size=0.2, random_state=42
)

In [13]:
print("Training data:", X_train.shape)
print("Testing data:", X_test.shape)

Training data: (533, 19)
Testing data: (134, 19)