<a href="https://colab.research.google.com/github/Anubhav-maurya6386/INTRANSHIP_TASK/blob/main/Data_PreprocessingStock_Prices_Data_Set.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# Import Required Libraries

In [1]:
import pandas as pd
import numpy as np

from sklearn.preprocessing import LabelEncoder, StandardScaler
from sklearn.model_selection import train_test_split

# Upload Dataset

In [3]:
df = pd.read_csv("/content/2) Stock Prices Data Set.csv")
df.head()

  symbol        date      open      high       low     close      volume
0    AAL  2014-01-02   25.0700   25.8200   25.0600   25.3600   8998943.0
1   AAPL  2014-01-02   79.3828   79.5756   78.8601   79.0185  58791957.0
2    AAP  2014-01-02  110.3600  111.8800  109.2900  109.7400    542711.0
3   ABBV  2014-01-02   52.1200   52.3300   51.5200   51.9800   4569061.0
4    ABC  2014-01-02   70.1100   70.2300   69.4800   69.8900   1148391.0

In [4]:
df.info()
df.describe()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 431255 entries, 0 to 431254
Data columns (total 7 columns):
 #   Column  Non-Null Count   Dtype
---  ------  --------------   -----
 0   symbol  431255 non-null  object
 1   date    431255 non-null  object
 2   open    431244 non-null  float64
 3   high    431247 non-null  float64
 4   low     431247 non-null  float64
 5   close   431254 non-null  float64
 6   volume  431254 non-null  float64
dtypes: float64(5), object(2)
memory usage: 23.0+ MB

,open,high,low,close,volume
count,431244.000000,431247.000000,431247.000000,431254.000000,4.312540e+05
mean,83.972328,84.748210,83.178348,83.991829,4.313892e+06
std,96.411170,97.243423,95.520821,96.413724,8.362643e+06
min,1.620000,1.690000,1.500000,1.590000,0.000000e+00
25%,41.150000,41.550000,40.760000,41.170000,1.091503e+06
50%,63.850000,64.420000,63.240000,63.850000,2.114756e+06
75%,95.750000,96.560000,94.880000,95.760000,4.333025e+06
max,1918.000000,1927.130000,1898.040000,1911.130000,6.182376e+08

# Handle Missing Values

In [5]:
df.isnull().sum()

symbol     0
date       0
open      11
high       8
low        8
close      1
volume     1
dtype: int64

In [6]:
df.fillna(df.mean(numeric_only=True), inplace=True)

# Encode Categorical Variables

In [7]:
df.select_dtypes(include=['object']).columns

Index(['symbol', 'date'], dtype='object')

In [8]:
le = LabelEncoder()

for col in df.select_dtypes(include=['object']).columns:
    df[col] = le.fit_transform(df[col])

# Separate Features and Target Variable

In [10]:
X = df.drop('close', axis=1)
y = df['close']

# Normalize / Standardize Numerical Features

In [11]:
scaler = StandardScaler()

X_scaled = scaler.fit_transform(X)

X_scaled = pd.DataFrame(X_scaled, columns=X.columns)

# Split Dataset into Training and Testing Sets

In [12]:
X_train, X_test, y_train, y_test = train_test_split(
    X_scaled,
    y,
    test_size=0.2,
    random_state=42
)

# Print Final Result

In [13]:
print("Data preprocessing completed successfully")

print("Training data shape:", X_train.shape)
print("Testing data shape:", X_test.shape)

Data preprocessing completed successfully
Training data shape: (345004, 6)
Testing data shape: (86251, 6)